HAI,	BTW testing return statements

HOW DUZ I testReturn YR code
    BOTH SAEM code AN 1
    O RLY?
	YA RLY
	    FOUND YR 10
	MEBBE BOTH SAEM code AN 2
	    FOUND YR 20
	MEBBE BOTH SAEM code AN 3
	    FOUND YR 30
	NO WAI
	    FOUND YR NOOB
    OIC
IF U SAY SO

VISIBLE testReturn 1 MKAY? MKAY?
VISIBLE testReturn 2 MKAY? MKAY?
VISIBLE testReturn 3 MKAY? MKAY?
VISIBLE testReturn NOOB MKAY? MKAY?

FOUND YR NOOB

KTHXBAI