This test checks that the logical AND n-ary operator produces the correct truth table.  Note that boolean values can not be cast to strings so this test first implicitly casts the resulting boolean values to integer values and prints these out instead.

HAI
	VISIBLE SUM OF 0 AN ALL OF FAIL AN FAIL AN FAIL AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF FAIL AN FAIL AN FAIL AN WIN MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF FAIL AN FAIL AN WIN AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF FAIL AN FAIL AN WIN AN WIN MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF FAIL AN WIN AN FAIL AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF FAIL AN WIN AN FAIL AN WIN MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF FAIL AN WIN AN WIN AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF FAIL AN WIN AN WIN AN WIN MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN FAIL AN FAIL AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN FAIL AN FAIL AN WIN MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN FAIL AN WIN AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN FAIL AN WIN AN WIN MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN WIN AN FAIL AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN WIN AN FAIL AN WIN MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN WIN AN WIN AN FAIL MKAY? MKAY?
	VISIBLE SUM OF 0 AN ALL OF WIN AN WIN AN WIN AN WIN MKAY? MKAY?
KTHXBAI
