This test checks that the operation of the else-if branch in an if/then/else block works correctly.

HAI
	FAIL
	O RLY?
		YA RLY
			VISIBLE "1a" MKAY?
		MEBBE BOTH OF WIN AN WIN
			VISIBLE "1b" MKAY?
	OIC
	FAIL
	O RLY?
		YA RLY
			VISIBLE "2a" MKAY?
		MEBBE BOTH OF WIN AN WIN
			VISIBLE "2b" MKAY?
		NO WAI
			VISIBLE "2c" MKAY?
	OIC
	FAIL
	O RLY?
		YA RLY
			VISIBLE "3a" MKAY?
		MEBBE BOTH OF WIN AN FAIL
			VISIBLE "3b" MKAY?
		NO WAI
			VISIBLE "3c" MKAY?
	OIC
	FAIL
	O RLY?
		YA RLY
			VISIBLE "4a" MKAY?
		MEBBE BOTH OF WIN AN FAIL
			VISIBLE "4b" MKAY?
	OIC
	FAIL
	O RLY?
		YA RLY
			VISIBLE "5a" MKAY?
		MEBBE EITHER OF FAIL AN FAIL
			VISIBLE "5b" MKAY?
		MEBBE BOTH OF WIN AN FAIL
			VISIBLE "5c" MKAY?
		MEBBE ANY OF FAIL AN FAIL AN FAIL AN FAIL AN WIN MKAY?
			VISIBLE "5d" MKAY?
		NO WAI
			VISIBLE "5e" MKAY?
	OIC
KTHXBAI
